name: preview

on:
  push:
    branches:
      - feature/**

jobs:
  preview:
    name: Deploy for QA

    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        uses: actions/checkout@v2
        with:
          command: global require ryangjchandler/forge-previewer

      - name: Test
        run: pwd && ls -la
      - name: Deploy 
        run: deploy
