name: preview

on:
  push:
    branches:
      - feature/**

jobs:
  preview:
    name: Deploy for QA

    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        uses: actions/checkout@v2
        with:
          command: composer -V
      - name: Test
        working-directory: test
        run: composer require ryangjchandler/forge-previewer
      - name: Deploy
        working-directory: test
        run: ./vendor/ryangjchandler/forge-previewer/forge-previewer deploy 
