name: preview

on:
  workflow_dispatch

jobs:
  preview:
    name: Deploy for QA

    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        uses: php-actions/composer@v6
      - name: Deploy
        run: | 
              composer require ryangjchandler/forge-previewer
              pwd && ls -la
              ./vendor/ryangjchandler/forge-previewer/forge-previewer deploy
              
